title: RedCup
description: "Redcup: An awesome Theme for Jekyll"

url: http://majo33.github.io
port: 3000
highlighter: pygments

permalink: /:year/:month/:day/:title.html
markdown: redcarpet

google_analytics: #

owner:
  name: majo33
